### ISSUE TITLE
Can't run on Windows

### ISSUE THREAD

**Issue by remram44** [takluyver/nbopen#13]
For some reason, nbopen doesn't install through setuptools; the 'nbopen' file created in Python\Scripts, with a shebang, is completely useless to Windows.

**Comment by takluyver** [comment]
I detest setuptools. You can use `python -m nbopen` at the command line, but especially on Windows, it's really infrastructure to allow double clicking a notebook file in the file manager. See the [win-install.py](https://github.com/takluyver/nbopen/blob/master/win-install.py) script.
