### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by flying-sheep** [takluyver/nbopen#21]
jupyter is out and nbopen 0.2 still uses ipython only

**Comment by takluyver** [comment]
It's not a priority - we've shimmed the IPython imports for now, so it still works (I'm still using it). I'll update the imports at some point.

**Comment by flying-sheep** [comment]
for me it doesn’t:

``pytb
/usr/lib/python3.4/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
Traceback (most recent call last):
  File "/usr/bin/nbopen", line 3, in <module>
    main()
  File "/usr/lib/python3.4/site-packages/nbopen.py", line 49, in main
    nbopen(args.filename, args.profile)
  File "/usr/lib/python3.4/site-packages/nbopen.py", line 26, in nbopen
    server_inf = find_best_server(filename, profile)
  File "/usr/lib/python3.4/site-packages/nbopen.py", line 14, in find_best_server
    servers = [si for si in notebookapp.list_running_servers(profile=profile) \
TypeError: list_running_servers() got an unexpected keyword argument 'profile'
```

**Comment by takluyver** [comment]
oh, right, I see. I'd forgotten I'd actually made a release of it, I just run from git.

**Comment by takluyver** [comment]
There you are, 0.3

**Comment by flying-sheep** [comment]
thanks!
