### ISSUE TITLE
Missing ipynb_icon_1024x1024.png for Retina displays

### ISSUE THREAD

**Issue by xoolive** [takluyver/nbopen#25]
When you have a Retina display, you don't deserve the ipynb icon in Finder... :cry: 
Could you provide a version of this file and adapt the installation script?

**Comment by takluyver** [comment]
What size do you have your icons? [According to Wikipedia](https://en.wikipedia.org/wiki/Retina_Display) the highest pixel density for a retina display on a laptop is 89 pixels/cm. The existing 512x512 icon should be over 5cm at that resolution.

If you need a bigger icon, feel free to make a pull request. The source for these icons is [here](https://github.com/ipython/ipython/blob/3.x/docs/resources/ipynb_icon_512x512.svg). Though I should probably also get round to updating to the Jupyter themed icons [here](https://github.com/jupyter/notebook/tree/master/docs/resources), but that's an orthogonal question.

**Comment by xoolive** [comment]
OK I will look at this next week ;)

By the way, here goes:

    prompt> sh osx-make-iconset.sh
    generating .icns file for mac app..
    NOTE: this will produce one warning message, because there is no
          1024x1024 icon that could be used to for the 'retina' 512x512 icon

About the orthogonal question, I would say they are both "not great" so, whatever :stuck_out_tongue_winking_eye:

**Comment by xoolive** [comment]
Well, actually... this warning message is hardcoded by the `osx-make-iconset.sh`
I made the 1024x1024 file but nothing is changed in the Finder.

Besides, I don't get how the Finder chooses the icon to display. The `setup.py` looks pretty much alright from what I found online, but I still have no icon appearing for my `*.ipynb` files.

This is a different issue, but for reference, I tried to compare what has been done for MacVim, and can't understand why the MacVim icon displays properly in any view (for the Finder) for Python files, but does not display in list view for Markdown files for example (rest format looks ok though...).

I would be curious to hear about people with Mac+Retina and properly displayed ipynb file icons.

**Comment by xoolive** [comment]
Oh actually I got the proper icon for the executable `nbopen` now...
Well, do you want me first to build a PR for the icon file in 1024x1024 and see how things go, or do you consider it as noise for now?

**Comment by takluyver** [comment]
If you've got the icons displaying now, I don't think there's any particular need to produce a 1024x1024 variant.

Not sure why you were having trouble getting it to display, but it's different for each platform, and I don't use a Mac, so I can't really help debug that!

**Comment by jfeist** [comment]
For me it works fine on two different macs, see, e.g., this screenshot:
<img width="105" alt="screen shot 2016-02-16 at 23 08 23" src="https://cloud.githubusercontent.com/assets/2112929/13092986/19b3c102-d503-11e5-946c-c0d88d12fa6c.png">

I made the pull request that added osx-make-iconset.sh - the warning message is just to inform you that the following warning (`nbopen.iconset:warning: Missing image for variant named 'icon' resource error: 'Failed to load image at 512@2x.'`) from iconutil is expected and nothing to worry about (as @takluyver said, the 512x512 icon should look perfectly fine even when the displayed icon is big).

Did you install (copy) nbopen.app into /Applications or $HOME/Applications? I have it in /Applications, not sure if that could make a difference?

**Comment by jfeist** [comment]
Ah I see that the problem was apparently resolved while I was typing this message. Sorry for the noise.

**Comment by xoolive** [comment]
Well the issue deserves to be closed, but the problem is not solved on my side.
I tried with both `/Applications` and `$HOME/Applications` and no icon :disappointed: 

Thank you and as you said, let's not add more noise here...

**Comment by takluyver** [comment]
If you two want to delve more into the problem, don't worry about the noise. :-)

**Comment by xoolive** [comment]
Thanks to @jfeist in private message:
> Did you maybe set a "bad" icon for .ipynb files manually at some point (maybe "Restore the original icon for an item" from https://support.apple.com/kb/PH13922?locale=en_US could help?), or maybe you have an old version of nbopen.app with a "bad" icon inside lying around somewhere? I would delete all old versions of nbopen.app (if any) and then maybe try the commands from here: https://gist.github.com/fabiofl/5873100

The second link to the gist with instructions to purge the cache of the Finder worked like a charm for me! :smile:
So I have now an icns file including the 512x2 version (so no warning) for everything (app file, ipynb files)

**Comment by linediconsine** [comment]
Super fast workaround :
$cp nbopen/icons/ipynb_icon_512x512.png nbopen/icons/ipynb_icon_1024x1024.png

**Comment by lucasfariaslf** [comment]
Well, I could easily solve it copying the 512x512 file and renaming it with 1024x1024:

`ipynb_icon_512x512(1).png --> ipynb_icon_1024x1024.png`
