### ISSUE TITLE
Server started via nbopen and pythonpath

### ISSUE THREAD

**Issue by vascotenner** [takluyver/nbopen#29]
Warning: This question might be not directly related to nbopen

When jupyter is launched by nbopen (launched by double clicking on a notebook in caja) , it does not have the pythonpath that I set in my bashrc, while bash is my "login terminal". 

Any clue what is going wrong or how to debug or for what keywords to search for?

**Comment by takluyver** [comment]
Are you using nbopen at the command line, or with GUI integration? I suspect it's the latter.

bashrc is only run in a terminal, so environment variables set there don't affect programs launched from a GUI. On Linux, you can set environment variables in `~/.profile`, which is run at login (at least for now, it looks like that might fail when distros switch to Wayland).

**Comment by vascotenner** [comment]
Sorry for the fuzz, I found the answer in the meantime [here](https://help.ubuntu.com/community/EnvironmentVariables). It turned out that setting PATH and PYTHONPATH in .bashrc works almost always, but not for programs launched from the graphical environment. For some reason I did not stumble in to this issue the last 10 years of using *unix.
