### ISSUE TITLE
cannot install from master

### ISSUE THREAD

**Issue by denfromufa** [takluyver/nbopen#43]
`pip install git+https://github.com/takluyver/nbopen` fails due to flit settings, no setup.py:

```
C:\Users\denis>pip install git+https://github.com/takluyver/nbopen
Collecting git+https://github.com/takluyver/nbopen
  Cloning https://github.com/takluyver/nbopen to c:\users\denis\appdata\local\temp\pip-a0_6h689-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\python\python35_64b\lib\tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\denis\\AppData\\Local\\Temp\\pip-a0_6h689-build\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\denis\AppData\Local\Temp\pip-a0_6h689-build\

C:\Users\denis>
```

**Comment by takluyver** [comment]
We're working* on PEP 517, which will allow pip to install projects from source without a setup.py. Until then, you either need to install it from PyPI, or get the repo and run `flit install` inside it.

(* Well, arguing about it. Put three programmers in a room, you get four opinions, as they say. But it is gradually getting closer)

**Comment by denfromufa** [comment]
@takluyver it would be nice if flit supported this at least until pip gets this feature:

flit install git+https://github.com/takluyver/nbopen

i did not understand how to use flit installfrom to install from github? there is no example in flit repository.

**Comment by takluyver** [comment]
Oh yeah, I'd forgotten about that. The syntax is: `flit installfrom github:takluyver/nbopen` .

The `installfrom` subcommand will be deprecated and eventually removed once PEP 517 goes through.
