### ISSUE TITLE
Autosave Error on Windows 

### ISSUE THREAD

**Issue by joonyoo** [takluyver/nbopen#44]
Using a windows 7 box,  after opening the notebook with nbopen and making a change I get the following notice and error:

![image](https://user-images.githubusercontent.com/17629707/29144711-9bb64b34-7cf5-11e7-9e71-e77211dc7345.png)

and "Unexpected error while saving file: Desktop\etc\etc  to notebook.ipynb [Errno 2] No such file or directory: 'C\\Users\\ipynb_checkpoints\\username\\Desktop\\etc\etc\notebook-checkpoint.ipynb

It appears the autosave is placing the ipynb_checkpoints in the wrong location of the path.

**Comment by takluyver** [comment]
That's weird, because I don't think nbopen does anything with the checkpoints folder. Are you opening a file from a checkpoints folder? And is the notebook server already running?

**Comment by erihanse** [comment]
Similar issue, see also https://github.com/jupyter/notebook/issues/2512.

When I open a notebook (from Windows Explorer) within a subdirectory of my home directory (using nbopen), I receive the following: 
![image](https://user-images.githubusercontent.com/9251274/30163267-a17dbeb8-93d8-11e7-8a7d-654d65f29f34.png)

I see that the url is the following:
> http://localhost:8888/notebooks/Documents%5CUntitled.ipynb

I saw somewhere else that we were supposed to be able to set default program for .ipynb files to be nbopen, but this will open the file in the above url (containing %5C). The notebook is displayed, but saving is not possible, resulting in above error. 

Another issue is that sometimes, when I try to open the file, it says that an existing server is already present:
> C:\Users\eriha\Documents>nbopen Untitled1.ipynb
> Using existing server at C:\Users\eriha
> [W 14:43:14.351 NotebookApp] server_extensions is deprecated, use nbserver_extensions

even though no server is running.

**Comment by takluyver** [comment]
I've just released 0.4.3, which should fix some issues on Windows, but I'm not sure if it fixes all of this. Can you upgrade and try?

**Comment by erihanse** [comment]
I believe it's fine now. Thanks.

**Comment by takluyver** [comment]
Thanks

**Comment by erihanse** [comment]
I might have been to fast. Now the kernel won't start with R, but the above error is fixed. It works without using nbopen though.

**Comment by takluyver** [comment]
How do you launch it when not using nbopen? My best guess would be that there's a difference in the environment when it's launched from a GUI versus launching from a command prompt.

**Comment by erihanse** [comment]
Windows explorer. I ran python -m nbopen.install_win as instructed. Here is some output from nbopen.exe:

```
[W 15:23:41.168 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170912152339 (::1) 2.00ms referer=http://localhost:8888/notebooks/OneDrive%20-%20Universitetet%20i%20Oslo/Skole/inf5100nsa/Week1/Assignment%20Week1.ipynb
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 15:23:44.111 NotebookApp] KernelRestarter: restarting kernel (1/5)
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 15:23:47.130 NotebookApp] KernelRestarter: restarting kernel (2/5)
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 15:23:50.146 NotebookApp] KernelRestarter: restarting kernel (3/5)
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[W 15:23:51.196 NotebookApp] Timeout waiting for kernel_info reply from 18a038bb-02bf-42d5-b851-a1c0415e4a6a
[I 15:23:53.186 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 18a038bb-02bf-42d5-b851-a1c0415e4a6a restarted
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
