### ISSUE TITLE
nbopen path

### ISSUE THREAD

**Issue by beew** [takluyver/nbopen#49]
Hi, It appears that double click to open ipynb only works if  c.NotebookApp.notebook_dir in jupyter_notebook_config.py is not set (default to $HOME), otherwise double click would open an empty notebook with 404 not found. It seems that nbopen search paths relative to $HOME. Is there a way to configure it so that it interprets paths as relative to notebook_dir ?

OS is Ubuntu 16.04 on two machines, in one I use anaconda, the other just installed with pip. 

Thanks.

**Comment by takluyver** [comment]
Thanks, that makes sense. I thought that passing the directory in would override the config, but it appears that it doesn't. I think I can see a better way to do it.
