### ISSUE TITLE
file manager integration broken?

### ISSUE THREAD

**Issue by NightFantomJ2** [takluyver/nbopen#56]
After installing nbopen (`nbopen myfile.ipynb` works in terminal), I also ran

`Linux/BSD: python3 -m nbopen.install_xdg`

Now nautilus changed the icons of .ipynb files but clicking them results in the following error:

Could not display “myfile.ipynb”.
There is no application installed for “IPython notebook” files.
Do you want to search for an application to open this file?

nbopen is in my path in my ~/.profile (`PATH="$HOME/anaconda3/bin/nbopen:$PATH"`), I'm running close to stock ubuntu 16.04

Did I miss something?

**Comment by NightFantomJ2** [comment]
Turns out I need `PATH="$HOME/anaconda3/bin:$PATH"` in my .profile (i.e. the containing folder) or it's not "on my path". My bad!

**Comment by takluyver** [comment]
I think I can change the way it works so that it doesn't need to be on path, which should make it simpler to use.
