### ISSUE TITLE
Missing icon for .ipynb notebooks (Ubuntu 18.10)

### ISSUE THREAD

**Issue by abhipn** [takluyver/nbopen#62]
I have installed the nbopen and executed `python3 -m nbopen.install_xdg` but the icons have not changed for .ipynb files.

**Comment by takluyver** [comment]
Have you rebooted since? I think sometimes the desktop doesn't pick up new icons straight away. It's kind of hard to debug, though.

**Comment by abhii-p** [comment]
I've tried rebooting but it seems to be not working for me.

**Comment by takluyver** [comment]
You could check XDG_DATA_HOME and that the icon files have ended up in the correct place under that. Beyond that, I don't really know how to debug this sort of issue - I've no idea where the code is in any desktop environment to look up the icon for a given file.
