### ISSUE TITLE
Double-clicking .ipynb file does not work with nbopen

### ISSUE THREAD

**Issue by mramadhito** [takluyver/nbopen#75]
Hi,

Any time I open an .ipynb file after I set the default app to open with as nbopen.exe, this error in the command prompt is produced. How can I troubleshoot this?

![image](https://user-images.githubusercontent.com/71415347/103259464-1afee300-49cc-11eb-9bbc-6de53d7390a0.png)

Thanks,
Garda

**Comment by takluyver** [comment]
Does it show that message and open anyway, or is it also not working? That message is a warning, not an error, so it's not necessarily a problem.

The [`install_win.py` script](https://github.com/takluyver/nbopen/blob/master/nbopen/install_win.py) sets it up to open with `pythonw.exe -m nbopen` rather than `nbopen.exe` - that should prevent a console window appearing.

**Comment by mramadhito** [comment]
So upon recording the command prompt again there is indeed an error message for a split second.

![image](https://user-images.githubusercontent.com/71415347/103346194-e707e880-4ac5-11eb-9bf1-b4826fd60f6c.png)

I ran the script above and it didn't change anything -- there's still an error and .ipynb files wouldn't open by double-clicking them. It looks like I'm missing a module from the error.

**Comment by takluyver** [comment]
Other people have been having similar errors to that - take a look at #61 and #69.

**Comment by mramadhito** [comment]
I re-installed both Anaconda and Python and I followed the instructions in #69. It looks like jupyter notebook needs to be activated before the double-click works.

**Comment by Greedquest** [comment]
@mramadhito have you tried what I suggested; change the registry key at

    Computer\HKEY_CURRENT_USER\SOFTWARE\Classes\Jupyter.nbopen\shell\open\command
to
```powershell
C:\Users\{USERNAME}\anaconda3\python.exe -m conda run -n base pythonw -m nbopen "%1"
```

(use whichever path to python the registry key currently references)

**Comment by mramadhito** [comment]
That works @Greedquest ! Thank you so much!

**Comment by Greedquest** [comment]
@mramadhito  great, I hoped it would! Maybe leave a thumbs up or something on the original thread so people know in future:
 https://github.com/takluyver/nbopen/issues/69#issuecomment-751688215

I should say the conda run command is in beta atm so may break, but I just wanted to solve the problem now! Also a terminal window may flash but it's fine to close it if it stays open, I asked about a fix over on SO [here](https://superuser.com/q/1614933/705597)
